import type { RefinanzierungsPfad, BundeslandProfil } from '@/lib/types';

// Bundesweite Pfade (für alle Bundesländer relevant)
const BUNDESWEITE_PFADE: RefinanzierungsPfad[] = [
  {
    id: 'sgb11_digital',
    titel: 'Digitalisierungsförderung Pflege',
    rechtsgrundlage: '§8 Abs. 8 SGB XI',
    maxBetrag: 'max. 12.000 EUR (einmalig)',
    deckungsgrad: 'gering',
    einmalig: true,
    voraussetzungen: [
      'Einrichtung erbringt Pflegeleistungen (SGB XI)',
      'Maßnahme dient der Digitalisierung des Pflegeprozesses',
      'IT-Sicherheit als Teil der Digitalisierung anerkannt',
    ],
    hinweis: 'Antragstellung bei zuständiger Pflegekasse. Fördersumme pro Einrichtung, nicht pro Träger.',
    antragsLink: 'https://www.gkv-spitzenverband.de',
  },
  {
    id: 'rueckenwind3',
    titel: 'rückenwind3 (ESF+) – Digitalisierung Sozialwirtschaft',
    rechtsgrundlage: 'ESF+ Förderperiode 2021–2027',
    maxBetrag: 'bis 800.000 EUR (50–70% Förderung)',
    deckungsgrad: 'mittel',
    einmalig: true,
    voraussetzungen: [
      'Träger der freien Wohlfahrtspflege',
      'Projektcharakter (kein laufender Betrieb)',
      'Digitalisierung als Projektziel',
    ],
    antragsLink: 'https://www.bagfw.de/rueckenwind',
  },
  {
    id: 'bafa_beratung',
    titel: 'BAFA Unternehmensberatung',
    rechtsgrundlage: 'Bundesförderung Beratung KMU',
    maxBetrag: 'max. 2.800 EUR (50–80% Förderung)',
    deckungsgrad: 'gering',
    einmalig: true,
    voraussetzungen: [
      'Für ISMS-Erstberatung geeignet',
      'Externe Berater:in muss BAFA-zugelassen sein',
    ],
    antragsLink: 'https://www.bafa.de',
  },
  {
    id: 'kfw_digital',
    titel: 'KfW-Digitalisierungskredit',
    rechtsgrundlage: 'KfW-Programm 380/390',
    maxBetrag: '3–5% Tilgungszuschuss',
    deckungsgrad: 'gering',
    einmalig: true,
    voraussetzungen: [
      'gGmbH oder e.V. mit wirtschaftlicher Tätigkeit',
      'Investitionscharakter (kein laufender Betrieb)',
    ],
    antragsLink: 'https://www.kfw.de',
  },
  {
    id: 'pflegesatz_sachkosten',
    titel: 'Pflegesatz-Sachkosten (laufend)',
    rechtsgrundlage: '§84 Abs. 2 SGB XI',
    deckungsgrad: 'mittel',
    einmalig: false,
    voraussetzungen: [
      'Pflegeeinrichtung mit SGB XI-Versorgungsvertrag',
      'Kosten als betriebsnotwendig nachweisbar',
      'Detaillierte Kostendokumentation erforderlich',
    ],
    hinweis: 'Durchsetzbarkeit stark bundesland- und pflegekassenabhängig. Verhandlungsergebnis nicht garantiert. Bei Ablehnung: Schiedsstelle (§76 SGB XI).',
  },
];

export const BUNDESLAND_PROFILE: BundeslandProfil[] = [
  {
    code: 'NW',
    name: 'Nordrhein-Westfalen',
    rdGesetz: 'RettG NRW',
    rdFinanzierungsModell: 'kostenerstattung',
    rdItKostenAnerkannt: true,
    rdHinweis: 'NRW kennt ein Kostenerstattungsmodell für den Rettungsdienst. IT-Sicherheitskosten können als Betriebskosten gegenüber den Kreisen geltend gemacht werden, sofern sie nachweislich dem Rettungsdienst zurechenbar sind. Empfehlung: Gemeinkostenumlage dokumentieren.',
    landesfoerderungIt: true,
    landesfoerderungLink: 'https://www.digitalland.nrw',
    pflegesatzPraxis: 'offen',
    pflegesatzHinweis: 'NRW-Pflegekassen haben IT-Sicherheit als Sachkostenpositionen bislang nicht pauschal abgelehnt. Detaillierte Nachweise erforderlich.',
    pfade: [
      ...BUNDESWEITE_PFADE,
      {
        id: 'nw_digitalland',
        titel: 'Digitalland.NRW – Förderung Sozialwirtschaft',
        rechtsgrundlage: 'EFRE/ESF NRW 2021–2027',
        maxBetrag: 'projektabhängig',
        deckungsgrad: 'mittel',
        einmalig: true,
        voraussetzungen: ['Träger mit Sitz in NRW', 'Digitalisierungsprojekt'],
        antragsLink: 'https://www.digitalland.nrw',
      },
    ],
  },
  {
    code: 'BY',
    name: 'Bayern',
    rdGesetz: 'BayRDG',
    rdFinanzierungsModell: 'pauschale',
    rdItKostenAnerkannt: false,
    rdHinweis: 'Bayern finanziert den Rettungsdienst über Benutzungsentgelte. IT-Sicherheitskosten sind in der Benutzungsentgelt-Kalkulation nicht explizit vorgesehen. Eine Geltendmachung als Betriebskosten ist argumentierbar, aber schwierig durchzusetzen. BRK (Bayerisches Rotes Kreuz) führt hierzu ggf. bereits Gespräche mit den Kostenträgern.',
    landesfoerderungIt: true,
    landesfoerderungLink: 'https://www.stmd.bayern.de/digitalisierung',
    pflegesatzPraxis: 'schwierig',
    pflegesatzHinweis: 'Bayerische Pflegekassen verweisen auf den externen Vergleich. Ohne Branchenstandard schwer durchsetzbar. BIHK bietet kostenlose Webinar-Unterstützung.',
    pfade: [
      ...BUNDESWEITE_PFADE,
      {
        id: 'by_digitalisierungsbonus',
        titel: 'Digitalisierungsbonus Bayern (sofern verlängert)',
        rechtsgrundlage: 'Bayerisches Förderprogramm',
        maxBetrag: 'bis 10.000 EUR',
        deckungsgrad: 'gering',
        einmalig: true,
        voraussetzungen: ['KMU oder gemeinnütziger Träger in Bayern', 'IT-Investition'],
        hinweis: 'Prüfen ob Programm in 2026 noch aktiv ist.',
        antragsLink: 'https://www.stmwi.bayern.de',
      },
    ],
  },
  {
    code: 'BW',
    name: 'Baden-Württemberg',
    rdGesetz: 'RDG BW',
    rdFinanzierungsModell: 'mischmodell',
    rdItKostenAnerkannt: false,
    rdHinweis: 'BW hat ein komplexes Mischmodell aus Kreisfinanzierung und Benutzungsentgelten. IT-Sicherheitskosten sind bislang nicht explizit adressiert. Gespräche mit Kostenträgern auf KV-Ebene empfohlen.',
    landesfoerderungIt: true,
    landesfoerderungLink: 'https://www.digital-bw.de',
    pflegesatzPraxis: 'offen',
    pflegesatzHinweis: 'BW-Pflegekassen sind gesprächsbereit, verlangen aber detaillierte Kostennachweise und Verhältnismäßigkeitsbegründung.',
    pfade: [...BUNDESWEITE_PFADE],
  },
  {
    code: 'HE',
    name: 'Hessen',
    rdGesetz: 'HRDG',
    rdFinanzierungsModell: 'kostenerstattung',
    rdItKostenAnerkannt: false,
    rdHinweis: 'Hessen nutzt Kostenerstattung. IT-Sicherheitskosten können prinzipiell als Betriebskosten des Rettungsdienstes geltend gemacht werden, Nachweis der Zurechenbarkeit erforderlich.',
    landesfoerderungIt: false,
    pflegesatzPraxis: 'unklar',
    pflegesatzHinweis: 'Keine belastbaren Informationen zu NIS-2-spezifischen Pflegesatzverhandlungen in Hessen vorhanden. Frühzeitiger Kontakt mit Landesverband empfohlen.',
    pfade: [...BUNDESWEITE_PFADE],
  },
  {
    code: 'RP',
    name: 'Rheinland-Pfalz',
    rdGesetz: 'RettDG RLP',
    rdFinanzierungsModell: 'pauschale',
    rdItKostenAnerkannt: false,
    rdHinweis: 'Rettungsdienst wird über Benutzungsentgelte finanziert. IT-Sicherheitskosten müssen gesondert argumentiert werden.',
    landesfoerderungIt: false,
    pflegesatzPraxis: 'unklar',
    pflegesatzHinweis: 'Kontakt mit DRK-Landesverband RLP empfohlen.',
    pfade: [...BUNDESWEITE_PFADE],
  },
  {
    code: 'SL',
    name: 'Saarland',
    rdGesetz: 'SRettG',
    rdFinanzierungsModell: 'mischmodell',
    rdItKostenAnerkannt: false,
    rdHinweis: 'Kleine Bundeslandfläche, wenige DRK-KV. Koordination über Landesverband empfohlen.',
    landesfoerderungIt: false,
    pflegesatzPraxis: 'unklar',
    pflegesatzHinweis: 'Zu wenige Daten verfügbar.',
    pfade: [...BUNDESWEITE_PFADE],
  },
  {
    code: 'SH',
    name: 'Schleswig-Holstein',
    rdGesetz: 'RDG SH',
    rdFinanzierungsModell: 'kostenerstattung',
    rdItKostenAnerkannt: false,
    rdHinweis: 'SH nutzt Kostenerstattungsmodell. Grundsätzlich günstig für IT-Kostenerstattung, aber NIS-2-spezifisch noch keine Klärung.',
    landesfoerderungIt: true,
    landesfoerderungLink: 'https://www.schleswig-holstein.de/digitalisierung',
    pflegesatzPraxis: 'offen',
    pflegesatzHinweis: 'SH gilt als vergleichsweise offen für neue Sachkostenpositionen.',
    pfade: [...BUNDESWEITE_PFADE],
  },
  {
    code: 'HH',
    name: 'Hamburg',
    rdGesetz: 'HmbRDG',
    rdFinanzierungsModell: 'kostenerstattung',
    rdItKostenAnerkannt: false,
    rdHinweis: 'Stadtsstaat, Rettungsdienst stark durch Feuerwehr geprägt. DRK in HH eher im Katastrophenschutz. Spezifische RD-Finanzierungsfragen mit Landesverband klären.',
    landesfoerderungIt: false,
    pflegesatzPraxis: 'unklar',
    pflegesatzHinweis: 'Stadtsstaat-Spezifika – individuelle Klärung erforderlich.',
    pfade: [...BUNDESWEITE_PFADE],
  },
  {
    code: 'HB',
    name: 'Bremen',
    rdGesetz: 'BremRDG',
    rdFinanzierungsModell: 'mischmodell',
    rdItKostenAnerkannt: false,
    rdHinweis: 'Kleiner Stadtsstaat. Individuelle Abstimmung mit Landesverband empfohlen.',
    landesfoerderungIt: false,
    pflegesatzPraxis: 'unklar',
    pflegesatzHinweis: 'Zu wenige Daten verfügbar.',
    pfade: [...BUNDESWEITE_PFADE],
  },
  {
    code: 'NI',
    name: 'Niedersachsen',
    rdGesetz: 'NRettDG',
    rdFinanzierungsModell: 'kostenerstattung',
    rdItKostenAnerkannt: false,
    rdHinweis: 'Niedersachsen finanziert über Kommunen. IT-Kosten als Betriebskosten argumentierbar. DRK-Landesverband Niedersachsen hat NIS-2 auf dem Radar.',
    landesfoerderungIt: true,
    landesfoerderungLink: 'https://digitalisierung.niedersachsen.de',
    pflegesatzPraxis: 'offen',
    pflegesatzHinweis: 'Eher offen für neue Sachkostenpositionen, Nachweis erforderlich.',
    pfade: [...BUNDESWEITE_PFADE],
  },
  {
    code: 'BB',
    name: 'Brandenburg',
    rdGesetz: 'BbgRettG',
    rdFinanzierungsModell: 'mischmodell',
    rdItKostenAnerkannt: false,
    rdHinweis: 'Ländliche Struktur, viele kleinere KV. Landesverband-Koordination besonders wichtig.',
    landesfoerderungIt: false,
    pflegesatzPraxis: 'unklar',
    pflegesatzHinweis: 'Zu wenige Daten verfügbar.',
    pfade: [...BUNDESWEITE_PFADE],
  },
  {
    code: 'MV',
    name: 'Mecklenburg-Vorpommern',
    rdGesetz: 'RVSG MV',
    rdFinanzierungsModell: 'mischmodell',
    rdItKostenAnerkannt: false,
    rdHinweis: 'Flächenland mit strukturellen Finanzierungsherausforderungen. Kooperationsansatz mit anderen KV empfohlen.',
    landesfoerderungIt: false,
    pflegesatzPraxis: 'schwierig',
    pflegesatzHinweis: 'Strukturell schwieriges Bundesland für Kostendurchsetzung.',
    pfade: [...BUNDESWEITE_PFADE],
  },
  {
    code: 'ST',
    name: 'Sachsen-Anhalt',
    rdGesetz: 'RettDG LSA',
    rdFinanzierungsModell: 'mischmodell',
    rdItKostenAnerkannt: false,
    rdHinweis: 'Landesverband-Koordination empfohlen.',
    landesfoerderungIt: false,
    pflegesatzPraxis: 'unklar',
    pflegesatzHinweis: 'Zu wenige Daten verfügbar.',
    pfade: [...BUNDESWEITE_PFADE],
  },
  {
    code: 'TH',
    name: 'Thüringen',
    rdGesetz: 'ThürRettG',
    rdFinanzierungsModell: 'mischmodell',
    rdItKostenAnerkannt: false,
    rdHinweis: 'Landesverband-Koordination empfohlen.',
    landesfoerderungIt: false,
    pflegesatzPraxis: 'unklar',
    pflegesatzHinweis: 'Zu wenige Daten verfügbar.',
    pfade: [...BUNDESWEITE_PFADE],
  },
  {
    code: 'SN',
    name: 'Sachsen',
    rdGesetz: 'SächsBRKG / RettDiG',
    rdFinanzierungsModell: 'mischmodell',
    rdItKostenAnerkannt: false,
    rdHinweis: 'Sachsen hat eine besondere Struktur – DRK integriert in Bevölkerungsschutzgesetz. Landesverband klären.',
    landesfoerderungIt: true,
    landesfoerderungLink: 'https://www.smwa.sachsen.de',
    pflegesatzPraxis: 'unklar',
    pflegesatzHinweis: 'Zu wenige Daten verfügbar.',
    pfade: [...BUNDESWEITE_PFADE],
  },
  {
    code: 'BE',
    name: 'Berlin',
    rdGesetz: 'RDG Berlin',
    rdFinanzierungsModell: 'kostenerstattung',
    rdItKostenAnerkannt: false,
    rdHinweis: 'Stadtsstaat. Rettungsdienst eng mit Berliner Feuerwehr verzahnt. DRK Berlin hat eigene Strukturen. Individuelle Klärung erforderlich.',
    landesfoerderungIt: true,
    landesfoerderungLink: 'https://www.berlin.de/digitalisierung',
    pflegesatzPraxis: 'offen',
    pflegesatzHinweis: 'Berlin gilt als vergleichsweise verhandlungsbereit.',
    pfade: [...BUNDESWEITE_PFADE],
  },
];

export function getBundeslandProfil(code: string): BundeslandProfil | undefined {
  return BUNDESLAND_PROFILE.find(bl => bl.code === code);
}
