import type { QuestionId } from '../types';

/** A single rule in the decision matrix */
export interface DecisionRule {
  id: string;
  description: { de: string; en: string };
  questionId: QuestionId;
  answerCodes: string[];
  policyPack: 'all' | 'public-bsi' | 'verbandslinie-konservativ';
  ruleRef: string;
  effectCode: string;
  effectText: { de: string; en: string };
  roadmapPacks: string[];
  priority: 'Hoch' | 'Mittel' | 'Niedrig';
}

export const decisionRules: DecisionRule[] = [
  // ── ORG-01: DRK-Typ ──
  { id: 'ORG-01-KV', description: { de: 'Kreisverband prüfen', en: 'Assess district association' }, questionId: 'ORG-01', answerCodes: ['KV'], policyPack: 'all', ruleRef: 'REG-050', effectCode: 'CTX_KV', effectText: { de: 'DRK-Kreisverbands-Flow aktivieren.', en: 'Activate district association flow.' }, roadmapPacks: ['P1'], priority: 'Mittel' },
  { id: 'ORG-01-TG', description: { de: 'Tochtergesellschaft prüfen', en: 'Assess subsidiary' }, questionId: 'ORG-01', answerCodes: ['TG'], policyPack: 'all', ruleRef: 'REG-002', effectCode: 'CTX_TG', effectText: { de: 'Einzelfall als operative oder Servicegesellschaft prüfen.', en: 'Assess as operational or service company case by case.' }, roadmapPacks: ['P2'], priority: 'Mittel' },
  { id: 'ORG-01-SG', description: { de: 'Servicegesellschaft prüfen', en: 'Assess service company' }, questionId: 'ORG-01', answerCodes: ['SG'], policyPack: 'all', ruleRef: 'REG-004', effectCode: 'CTX_SG', effectText: { de: 'Servicegesellschaft nicht automatisch direkt betroffen; Shared-IT und Lieferkette prüfen.', en: 'Service company not automatically directly affected; check shared IT and supply chain.' }, roadmapPacks: ['P8', 'P11'], priority: 'Mittel' },

  // ── ORG-02: RD-Organisation ──
  { id: 'ORG-02-EV', description: { de: 'RD als Abteilung im e.V.', en: 'EMS as department in association' }, questionId: 'ORG-02', answerCodes: ['EV_ABT'], policyPack: 'all', ruleRef: 'REG-001', effectCode: 'LEGAL_SCOPE_WHOLE_ENTITY', effectText: { de: 'Juristischer Scope = gesamter Rechtsträger.', en: 'Legal scope = entire legal entity.' }, roadmapPacks: ['P2', 'P11'], priority: 'Hoch' },
  { id: 'ORG-02-GGMBH', description: { de: 'RD in eigener gGmbH', en: 'EMS in separate company' }, questionId: 'ORG-02', answerCodes: ['GGMBH'], policyPack: 'all', ruleRef: 'REG-002', effectCode: 'LEGAL_SCOPE_OPERATING_ENTITY', effectText: { de: 'Juristischer Scope = operative Gesellschaft.', en: 'Legal scope = operating company.' }, roadmapPacks: ['P2'], priority: 'Hoch' },
  { id: 'ORG-02-SPLIT', description: { de: 'RD auf mehrere Einheiten verteilt', en: 'EMS split across entities' }, questionId: 'ORG-02', answerCodes: ['SPLIT'], policyPack: 'all', ruleRef: 'REG-003', effectCode: 'FLAG_COMPLEX_STRUCTURE', effectText: { de: 'Komplexe Verbundstruktur; konservative Bewertung und juristische Review erforderlich.', en: 'Complex group structure; conservative assessment and legal review required.' }, roadmapPacks: ['P11', 'P12'], priority: 'Hoch' },
  { id: 'ORG-02-NORD', description: { de: 'Kein Rettungsdienst', en: 'No EMS' }, questionId: 'ORG-02', answerCodes: ['NO_RD'], policyPack: 'all', ruleRef: 'REG-040', effectCode: 'NO_RD_TRIGGER', effectText: { de: 'Kein rettungsdienstlicher Trigger aus diesem Tool.', en: 'No EMS trigger from this tool.' }, roadmapPacks: ['P1'], priority: 'Mittel' },

  // ── ORG-03: Einheiten im Verbund ──
  { id: 'ORG-03-ONE', description: { de: 'Einfache Struktur', en: 'Simple structure' }, questionId: 'ORG-03', answerCodes: ['ONE'], policyPack: 'all', ruleRef: 'REG-050', effectCode: 'SIMPLE_STRUCTURE', effectText: { de: 'Einfache Verbundstruktur; Standard-Flow.', en: 'Simple group structure; standard flow.' }, roadmapPacks: ['P1'], priority: 'Niedrig' },
  { id: 'ORG-03-MED', description: { de: 'Moderate Komplexität', en: 'Moderate complexity' }, questionId: 'ORG-03', answerCodes: ['TWO_THREE'], policyPack: 'all', ruleRef: 'REG-050', effectCode: 'MODERATE_COMPLEXITY', effectText: { de: 'Mehrfachprüfung von Rechtsträger und Shared IT einplanen.', en: 'Plan for multiple legal entity and shared IT checks.' }, roadmapPacks: ['P1', 'P2'], priority: 'Mittel' },
  { id: 'ORG-03-HIGH', description: { de: 'Komplexe Verbundstruktur', en: 'Complex group structure' }, questionId: 'ORG-03', answerCodes: ['FOUR_PLUS'], policyPack: 'all', ruleRef: 'REG-003', effectCode: 'FLAG_COMPLEX_STRUCTURE', effectText: { de: 'Komplexe Verbundstruktur; zentrale Scope-Entscheidung dokumentieren.', en: 'Complex group structure; document central scope decision.' }, roadmapPacks: ['P11', 'P12'], priority: 'Hoch' },

  // ── ORG-04: Personal ──
  { id: 'ORG-04-SAME', description: { de: 'Saubere Personalzuordnung', en: 'Clean personnel assignment' }, questionId: 'ORG-04', answerCodes: ['SAME'], policyPack: 'all', ruleRef: 'REG-050', effectCode: 'PERSONNEL_CLEAN', effectText: { de: 'Saubere Zuordnung; keine Zusatzeskalation.', en: 'Clean assignment; no additional escalation.' }, roadmapPacks: ['P2'], priority: 'Niedrig' },
  { id: 'ORG-04-OTHER', description: { de: 'Personal von anderem Rechtsträger', en: 'Personnel from different entity' }, questionId: 'ORG-04', answerCodes: ['OTHER', 'MIXED'], policyPack: 'all', ruleRef: 'REG-003', effectCode: 'FLAG_COMPLEX_STRUCTURE', effectText: { de: 'Personal und Betrieb fallen auseinander; konservative Bewertung.', en: 'Personnel and operations diverge; conservative assessment.' }, roadmapPacks: ['P11', 'P12'], priority: 'Hoch' },

  // ── ORG-05: IT-Verantwortung ──
  { id: 'ORG-05-CENTRAL-EV', description: { de: 'Zentrale IT im e.V.', en: 'Central IT in association' }, questionId: 'ORG-05', answerCodes: ['CENTRAL_EV'], policyPack: 'all', ruleRef: 'REG-031', effectCode: 'PRESUME_SHARED_IT', effectText: { de: 'Shared-IT-Vermutung; technischer Scope ausweiten.', en: 'Shared IT presumption; extend technical scope.' }, roadmapPacks: ['P4', 'P5', 'P6', 'P7'], priority: 'Hoch' },
  { id: 'ORG-05-CENTRAL-MSP', description: { de: 'Zentraler MSP', en: 'Central MSP' }, questionId: 'ORG-05', answerCodes: ['CENTRAL_MSP'], policyPack: 'all', ruleRef: 'REG-031', effectCode: 'PRESUME_SHARED_IT_SUPPLIER', effectText: { de: 'Shared-IT- und Lieferkettenprüfung auslösen.', en: 'Trigger shared IT and supply chain review.' }, roadmapPacks: ['P8', 'P10'], priority: 'Hoch' },
  { id: 'ORG-05-DECENTRAL', description: { de: 'Dezentrale IT', en: 'Decentralized IT' }, questionId: 'ORG-05', answerCodes: ['DECENTRAL'], policyPack: 'all', ruleRef: 'REG-050', effectCode: 'DECENTRAL_IT', effectText: { de: 'Begrenzter Scope plausibler; Trennungsnachweis dennoch prüfen.', en: 'Limited scope more plausible; still verify separation evidence.' }, roadmapPacks: ['P10'], priority: 'Mittel' },
  { id: 'ORG-05-MIXED', description: { de: 'Gemischtes IT-Modell', en: 'Mixed IT model' }, questionId: 'ORG-05', answerCodes: ['MIXED'], policyPack: 'all', ruleRef: 'REG-003', effectCode: 'FLAG_COMPLEX_STRUCTURE', effectText: { de: 'Gemischtes IT-Betriebsmodell; Scope konservativ bewerten.', en: 'Mixed IT operating model; assess scope conservatively.' }, roadmapPacks: ['P11', 'P12'], priority: 'Hoch' },

  // ── ORG-06: Zentraler IT-Betrieb ──
  { id: 'ORG-06-YES', description: { de: 'Zentraler IT-Betrieb ja', en: 'Central IT operations yes' }, questionId: 'ORG-06', answerCodes: ['YES'], policyPack: 'all', ruleRef: 'REG-031', effectCode: 'TECH_SCOPE_SHARED', effectText: { de: 'Technischer Scope erweitert sich auf den Shared-IT-Layer.', en: 'Technical scope extends to the shared IT layer.' }, roadmapPacks: ['P4', 'P5', 'P6', 'P7', 'P8'], priority: 'Hoch' },
  { id: 'ORG-06-PARTIAL', description: { de: 'Teilweise zentraler IT-Betrieb', en: 'Partially central IT' }, questionId: 'ORG-06', answerCodes: ['PARTIAL'], policyPack: 'all', ruleRef: 'REG-033', effectCode: 'TECH_SCOPE_PARTIAL', effectText: { de: 'Partielle Trennung; Ergebnis C-Kandidat.', en: 'Partial separation; Outcome C candidate.' }, roadmapPacks: ['P10', 'P11'], priority: 'Hoch' },
  { id: 'ORG-06-NO', description: { de: 'Kein zentraler IT-Betrieb', en: 'No central IT operations' }, questionId: 'ORG-06', answerCodes: ['NO'], policyPack: 'all', ruleRef: 'REG-032', effectCode: 'TECH_SCOPE_POSSIBLY_LIMITED', effectText: { de: 'Begrenzter Scope möglich, wenn weitere Trennkriterien erfüllt.', en: 'Limited scope possible if further separation criteria met.' }, roadmapPacks: ['P10'], priority: 'Mittel' },

  // ── OPS-01: Rettungsdienst (policy-pack-sensitiv) ──
  { id: 'OPS-01-YES-BSI', description: { de: 'RD ja (Public-BSI)', en: 'EMS yes (Public-BSI)' }, questionId: 'OPS-01', answerCodes: ['YES'], policyPack: 'public-bsi', ruleRef: 'REG-010', effectCode: 'RULESENSITIVE_NO_AUTO_TRIGGER', effectText: { de: 'Unter Public-BSI kein automatischer Sektor-Trigger aus Rettungsdienst.', en: 'Under Public-BSI, no automatic sector trigger from EMS.' }, roadmapPacks: ['P11'], priority: 'Hoch' },
  { id: 'OPS-01-YES-VL', description: { de: 'RD ja (Verbandslinie)', en: 'EMS yes (Association Guideline)' }, questionId: 'OPS-01', answerCodes: ['YES'], policyPack: 'verbandslinie-konservativ', ruleRef: 'REG-011', effectCode: 'SECTOR_TRIGGER_RD', effectText: { de: 'Rettungsdienstlicher Sektor-Trigger gesetzt.', en: 'EMS sector trigger set.' }, roadmapPacks: ['P2', 'P3'], priority: 'Hoch' },
  { id: 'OPS-01-NO', description: { de: 'Kein RD', en: 'No EMS' }, questionId: 'OPS-01', answerCodes: ['NO'], policyPack: 'all', ruleRef: 'REG-040', effectCode: 'NO_RD_TRIGGER', effectText: { de: 'Kein rettungsdienstlicher Sektor-Trigger.', en: 'No EMS sector trigger.' }, roadmapPacks: ['P1'], priority: 'Mittel' },

  // ── OPS-02: Krankentransport ──
  { id: 'OPS-02-YES', description: { de: 'Krankentransport ja', en: 'Patient transport yes' }, questionId: 'OPS-02', answerCodes: ['YES'], policyPack: 'all', ruleRef: 'REG-003', effectCode: 'FLAG_REVIEW_TRANSPORT', effectText: { de: 'Konstellation für juristische Review markieren.', en: 'Mark constellation for legal review.' }, roadmapPacks: ['P11'], priority: 'Mittel' },

  // ── OPS-03: Einsatznahe Systeme ──
  { id: 'OPS-03-YES', description: { de: 'Einsatznahe Systeme vorhanden', en: 'Mission-critical systems present' }, questionId: 'OPS-03', answerCodes: ['YES'], policyPack: 'all', ruleRef: 'REG-050', effectCode: 'CRITICAL_RD_SYSTEMS', effectText: { de: 'Bei Betroffenheit gehören diese Systeme zwingend in den Scope.', en: 'If affected, these systems must be in scope.' }, roadmapPacks: ['P5', 'P6', 'P7', 'P9'], priority: 'Hoch' },
  { id: 'OPS-03-PARTIAL', description: { de: 'Einsatznahe Systeme teilweise', en: 'Mission-critical systems partially' }, questionId: 'OPS-03', answerCodes: ['PARTIAL'], policyPack: 'all', ruleRef: 'REG-050', effectCode: 'INVENTORY_REQUIRED', effectText: { de: 'Systeminventar und Zuordnung vervollständigen.', en: 'Complete system inventory and assignment.' }, roadmapPacks: ['P9', 'P12'], priority: 'Mittel' },

  // ── OPS-04: Pflege ──
  { id: 'OPS-04-YES', description: { de: 'Pflegeleistungen ja', en: 'Care services yes' }, questionId: 'OPS-04', answerCodes: ['YES'], policyPack: 'all', ruleRef: 'REG-003', effectCode: 'FLAG_OTHER_SECTOR_REVIEW', effectText: { de: 'Zusätzliche sektorale Prüfung außerhalb des RD-Kerns vormerken.', en: 'Schedule additional sectoral review outside EMS core.' }, roadmapPacks: ['P11'], priority: 'Mittel' },

  // ── OPS-05: Kitas ──
  { id: 'OPS-05-YES', description: { de: 'Kitas/Jugendhilfe ja', en: 'Childcare yes' }, questionId: 'OPS-05', answerCodes: ['YES'], policyPack: 'all', ruleRef: 'REG-050', effectCode: 'MAP_SHARED_IT_ONLY', effectText: { de: 'Für Shared-IT-Scope mappen.', en: 'Map for shared IT scope.' }, roadmapPacks: ['P5', 'P9'], priority: 'Niedrig' },

  // ── OPS-06: KatS ──
  { id: 'OPS-06-YES', description: { de: 'KatS mit IT ja', en: 'Disaster relief IT yes' }, questionId: 'OPS-06', answerCodes: ['YES'], policyPack: 'all', ruleRef: 'REG-050', effectCode: 'FLAG_CRISIS_CONTINUITY', effectText: { de: 'Krisenkommunikation/BCM mit betrachten.', en: 'Include crisis communication/BCM.' }, roadmapPacks: ['P6', 'P7'], priority: 'Mittel' },


  // ── THR-01: VZÄ ──
  { id: 'THR-01-LT50', description: { de: 'Unter 50 VZÄ', en: 'Under 50 FTEs' }, questionId: 'THR-01', answerCodes: ['LT50'], policyPack: 'all', ruleRef: 'REG-022', effectCode: 'THRESHOLD_STAFF_BELOW', effectText: { de: 'Unterhalb des Personal-Schwellenwertes.', en: 'Below staff threshold.' }, roadmapPacks: ['P2'], priority: 'Hoch' },
  { id: 'THR-01-MED', description: { de: '50-249 VZÄ', en: '50-249 FTEs' }, questionId: 'THR-01', answerCodes: ['50_249'], policyPack: 'all', ruleRef: 'REG-020', effectCode: 'THRESHOLD_IMPORTANT_STAFF', effectText: { de: 'Schwelle wichtige Einrichtung über Personal erreichbar.', en: 'Important entity threshold reachable via staff.' }, roadmapPacks: ['P2', 'P3'], priority: 'Hoch' },
  { id: 'THR-01-HIGH', description: { de: '250+ VZÄ', en: '250+ FTEs' }, questionId: 'THR-01', answerCodes: ['250PLUS'], policyPack: 'all', ruleRef: 'REG-021', effectCode: 'THRESHOLD_ESSENTIAL_STAFF', effectText: { de: 'Schwelle besonders wichtige Einrichtung über Personal erreichbar.', en: 'Essential entity threshold reachable via staff.' }, roadmapPacks: ['P2', 'P3'], priority: 'Hoch' },

  // ── THR-02: Umsatz ──
  { id: 'THR-02-LT10', description: { de: 'Umsatz unter 10M', en: 'Revenue under 10M' }, questionId: 'THR-02', answerCodes: ['LT10'], policyPack: 'all', ruleRef: 'REG-022', effectCode: 'THRESHOLD_REV_BELOW', effectText: { de: 'Unterhalb des finanziellen Triggers.', en: 'Below financial trigger.' }, roadmapPacks: ['P2'], priority: 'Mittel' },
  { id: 'THR-02-MED', description: { de: 'Umsatz 10-50M', en: 'Revenue 10-50M' }, questionId: 'THR-02', answerCodes: ['10_50'], policyPack: 'all', ruleRef: 'REG-020', effectCode: 'THRESHOLD_IMPORTANT_REVENUE', effectText: { de: 'Finanzieller Trigger für wichtige Einrichtung möglich.', en: 'Financial trigger for important entity possible.' }, roadmapPacks: ['P2'], priority: 'Hoch' },
  { id: 'THR-02-HIGH', description: { de: 'Umsatz über 50M', en: 'Revenue over 50M' }, questionId: 'THR-02', answerCodes: ['GT50'], policyPack: 'all', ruleRef: 'REG-021', effectCode: 'THRESHOLD_ESSENTIAL_REVENUE', effectText: { de: 'Finanzieller Trigger für besonders wichtige Einrichtung möglich.', en: 'Financial trigger for essential entity possible.' }, roadmapPacks: ['P2'], priority: 'Hoch' },

  // ── THR-03: Bilanzsumme ──
  { id: 'THR-03-LT10', description: { de: 'Bilanzsumme unter 10M', en: 'Balance under 10M' }, questionId: 'THR-03', answerCodes: ['LT10'], policyPack: 'all', ruleRef: 'REG-022', effectCode: 'THRESHOLD_BAL_BELOW', effectText: { de: 'Unterhalb des finanziellen Triggers.', en: 'Below financial trigger.' }, roadmapPacks: ['P2'], priority: 'Mittel' },
  { id: 'THR-03-MED', description: { de: 'Bilanzsumme 10-43M', en: 'Balance 10-43M' }, questionId: 'THR-03', answerCodes: ['10_43'], policyPack: 'all', ruleRef: 'REG-020', effectCode: 'THRESHOLD_IMPORTANT_BALANCE', effectText: { de: 'Finanzieller Trigger für wichtige Einrichtung möglich.', en: 'Financial trigger for important entity possible.' }, roadmapPacks: ['P2'], priority: 'Hoch' },
  { id: 'THR-03-HIGH', description: { de: 'Bilanzsumme über 43M', en: 'Balance over 43M' }, questionId: 'THR-03', answerCodes: ['GT43'], policyPack: 'all', ruleRef: 'REG-021', effectCode: 'THRESHOLD_ESSENTIAL_BALANCE', effectText: { de: 'Finanzieller Trigger für besonders wichtige Einrichtung möglich.', en: 'Financial trigger for essential entity possible.' }, roadmapPacks: ['P2'], priority: 'Hoch' },

  // ── THR-04: Datenbelastbarkeit ──
  { id: 'THR-04-DOC', description: { de: 'Daten dokumentiert', en: 'Data documented' }, questionId: 'THR-04', answerCodes: ['DOC'], policyPack: 'all', ruleRef: 'REG-050', effectCode: 'THRESHOLD_DATA_OK', effectText: { de: 'Datenlage ausreichend für Entscheidung.', en: 'Data sufficient for decision.' }, roadmapPacks: ['P2'], priority: 'Hoch' },
  { id: 'THR-04-EST', description: { de: 'Daten geschätzt', en: 'Data estimated' }, questionId: 'THR-04', answerCodes: ['EST'], policyPack: 'all', ruleRef: 'REG-023', effectCode: 'FLAG_DATA_WEAK', effectText: { de: 'Betroffenheit nicht final; Ergebnis D-Kandidat.', en: 'Affectedness not final; Outcome D candidate.' }, roadmapPacks: ['P12'], priority: 'Hoch' },
  { id: 'THR-04-MISS', description: { de: 'Daten fehlen', en: 'Data missing' }, questionId: 'THR-04', answerCodes: ['MISS'], policyPack: 'all', ruleRef: 'REG-023', effectCode: 'RESULT_D_MISSING_THRESHOLD_DATA', effectText: { de: 'Ohne belastbare Daten keine belastbare Entscheidung.', en: 'No reliable decision without reliable data.' }, roadmapPacks: ['P12'], priority: 'Hoch' },

  // ── THR-05: Datengranularität ──
  { id: 'THR-05-ENTITY', description: { de: 'Daten je Rechtsträger', en: 'Data per entity' }, questionId: 'THR-05', answerCodes: ['ENTITY'], policyPack: 'all', ruleRef: 'REG-050', effectCode: 'ENTITY_DATA_READY', effectText: { de: 'Saubere Schwellenwertprüfung möglich.', en: 'Clean threshold assessment possible.' }, roadmapPacks: ['P2'], priority: 'Mittel' },
  { id: 'THR-05-CONSOL', description: { de: 'Nur konsolidiert', en: 'Consolidated only' }, questionId: 'THR-05', answerCodes: ['CONSOL'], policyPack: 'all', ruleRef: 'REG-023', effectCode: 'FLAG_NEED_ENTITY_SPLIT', effectText: { de: 'Rechtsträgerbezogene Schwellenwertprüfung nachziehen; Ergebnis D-Kandidat.', en: 'Entity-based threshold review needed; Outcome D candidate.' }, roadmapPacks: ['P12'], priority: 'Hoch' },
  { id: 'THR-05-MIXED', description: { de: 'Teilweise', en: 'Partially' }, questionId: 'THR-05', answerCodes: ['MIXED'], policyPack: 'all', ruleRef: 'REG-023', effectCode: 'FLAG_PARTIAL_ENTITY_SPLIT', effectText: { de: 'Datenlücke schließen und konservativ bewerten.', en: 'Close data gap and assess conservatively.' }, roadmapPacks: ['P12'], priority: 'Hoch' },

  // ── IT-01 through IT-13: IT-Kopplung ──
  // IT-01: Identity
  { id: 'IT-01-YES', description: { de: 'Shared Identity ja', en: 'Shared identity yes' }, questionId: 'IT-01', answerCodes: ['YES'], policyPack: 'all', ruleRef: 'REG-030', effectCode: 'TECH_SCOPE_SHARED_ID', effectText: { de: 'Shared Identity zieht technischen Scope hoch.', en: 'Shared identity raises technical scope.' }, roadmapPacks: ['P4', 'P10'], priority: 'Hoch' },
  { id: 'IT-01-PARTIAL', description: { de: 'Shared Identity teilweise', en: 'Shared identity partially' }, questionId: 'IT-01', answerCodes: ['PARTIAL'], policyPack: 'all', ruleRef: 'REG-030', effectCode: 'TECH_SCOPE_PARTIAL_ID', effectText: { de: 'Partielle Shared Identity; Ergebnis C-Kandidat.', en: 'Partial shared identity; Outcome C candidate.' }, roadmapPacks: ['P4', 'P10'], priority: 'Hoch' },
  { id: 'IT-01-NO', description: { de: 'Identity getrennt', en: 'Identity separated' }, questionId: 'IT-01', answerCodes: ['NO'], policyPack: 'all', ruleRef: 'REG-032', effectCode: 'SPLIT_CRITERION_ID_OK', effectText: { de: 'Ein Trennkriterium erfüllt.', en: 'One separation criterion met.' }, roadmapPacks: ['P10'], priority: 'Mittel' },

  // IT-02: Tenant
  { id: 'IT-02-YES', description: { de: 'Shared Tenant ja', en: 'Shared tenant yes' }, questionId: 'IT-02', answerCodes: ['YES'], policyPack: 'all', ruleRef: 'REG-031', effectCode: 'TECH_SCOPE_SHARED_TENANT', effectText: { de: 'Shared Tenant spricht gegen harte Trennung.', en: 'Shared tenant argues against hard separation.' }, roadmapPacks: ['P4', 'P10'], priority: 'Hoch' },
  { id: 'IT-02-PARTIAL', description: { de: 'Shared Tenant teilweise', en: 'Shared tenant partially' }, questionId: 'IT-02', answerCodes: ['PARTIAL'], policyPack: 'all', ruleRef: 'REG-033', effectCode: 'TECH_SCOPE_PARTIAL_TENANT', effectText: { de: 'Partielle Trennung; Ergebnis C-Kandidat.', en: 'Partial separation; Outcome C candidate.' }, roadmapPacks: ['P4', 'P10'], priority: 'Hoch' },

  // IT-03: Network
  { id: 'IT-03-YES', description: { de: 'Shared Netzwerk ja', en: 'Shared network yes' }, questionId: 'IT-03', answerCodes: ['YES'], policyPack: 'all', ruleRef: 'REG-031', effectCode: 'TECH_SCOPE_SHARED_NETWORK', effectText: { de: 'Gemeinsame Netzgrenzen sprechen gegen harte Trennung.', en: 'Shared network boundaries argue against hard separation.' }, roadmapPacks: ['P5', 'P10'], priority: 'Hoch' },
  { id: 'IT-03-PARTIAL', description: { de: 'Shared Netzwerk teilweise', en: 'Shared network partially' }, questionId: 'IT-03', answerCodes: ['PARTIAL'], policyPack: 'all', ruleRef: 'REG-033', effectCode: 'TECH_SCOPE_PARTIAL_NETWORK', effectText: { de: 'Partielle Netztrennung; Ergebnis C-Kandidat.', en: 'Partial network separation; Outcome C candidate.' }, roadmapPacks: ['P5', 'P10'], priority: 'Hoch' },

  // IT-04: Backup
  { id: 'IT-04-YES', description: { de: 'Shared Backup ja', en: 'Shared backup yes' }, questionId: 'IT-04', answerCodes: ['YES'], policyPack: 'all', ruleRef: 'REG-031', effectCode: 'TECH_SCOPE_SHARED_BACKUP', effectText: { de: 'Shared Backup spricht gegen harte Trennung.', en: 'Shared backup argues against hard separation.' }, roadmapPacks: ['P6', 'P10'], priority: 'Hoch' },
  { id: 'IT-04-PARTIAL', description: { de: 'Shared Backup teilweise', en: 'Shared backup partially' }, questionId: 'IT-04', answerCodes: ['PARTIAL'], policyPack: 'all', ruleRef: 'REG-033', effectCode: 'TECH_SCOPE_PARTIAL_BACKUP', effectText: { de: 'Partielle Trennung; Ergebnis C-Kandidat.', en: 'Partial separation; Outcome C candidate.' }, roadmapPacks: ['P6', 'P10'], priority: 'Hoch' },

  // IT-05: Admin
  { id: 'IT-05-YES', description: { de: 'Shared Admin ja', en: 'Shared admin yes' }, questionId: 'IT-05', answerCodes: ['YES'], policyPack: 'all', ruleRef: 'REG-031', effectCode: 'TECH_SCOPE_SHARED_ADMIN', effectText: { de: 'Gemeinsame privilegierte Administration spricht klar gegen harte Trennung.', en: 'Shared privileged administration clearly argues against hard separation.' }, roadmapPacks: ['P4', 'P10'], priority: 'Hoch' },
  { id: 'IT-05-PARTIAL', description: { de: 'Shared Admin teilweise', en: 'Shared admin partially' }, questionId: 'IT-05', answerCodes: ['PARTIAL'], policyPack: 'all', ruleRef: 'REG-033', effectCode: 'TECH_SCOPE_PARTIAL_ADMIN', effectText: { de: 'Partielle Trennung; Ergebnis C-Kandidat.', en: 'Partial separation; Outcome C candidate.' }, roadmapPacks: ['P4', 'P10'], priority: 'Hoch' },

  // IT-06: Hosting
  { id: 'IT-06-YES', description: { de: 'Shared Hosting ja', en: 'Shared hosting yes' }, questionId: 'IT-06', answerCodes: ['YES'], policyPack: 'all', ruleRef: 'REG-031', effectCode: 'TECH_SCOPE_SHARED_HOSTING', effectText: { de: 'Shared Hosting zieht technischen Scope hoch.', en: 'Shared hosting raises technical scope.' }, roadmapPacks: ['P5', 'P6', 'P10'], priority: 'Hoch' },
  { id: 'IT-06-PARTIAL', description: { de: 'Shared Hosting teilweise', en: 'Shared hosting partially' }, questionId: 'IT-06', answerCodes: ['PARTIAL'], policyPack: 'all', ruleRef: 'REG-033', effectCode: 'TECH_SCOPE_PARTIAL_HOSTING', effectText: { de: 'Partielle Trennung; Ergebnis C-Kandidat.', en: 'Partial separation; Outcome C candidate.' }, roadmapPacks: ['P5', 'P6', 'P10'], priority: 'Hoch' },

  // IT-07: Endpoint/MDM
  { id: 'IT-07-YES', description: { de: 'Shared Endpoint ja', en: 'Shared endpoint yes' }, questionId: 'IT-07', answerCodes: ['YES'], policyPack: 'all', ruleRef: 'REG-031', effectCode: 'TECH_SCOPE_SHARED_ENDPOINT', effectText: { de: 'Shared Endpoint-/MDM-Management spricht gegen harte Trennung.', en: 'Shared endpoint/MDM management argues against hard separation.' }, roadmapPacks: ['P4', 'P10'], priority: 'Hoch' },
  { id: 'IT-07-PARTIAL', description: { de: 'Shared Endpoint teilweise', en: 'Shared endpoint partially' }, questionId: 'IT-07', answerCodes: ['PARTIAL'], policyPack: 'all', ruleRef: 'REG-033', effectCode: 'TECH_SCOPE_PARTIAL_ENDPOINT', effectText: { de: 'Partielle Trennung; Ergebnis C-Kandidat.', en: 'Partial separation; Outcome C candidate.' }, roadmapPacks: ['P4', 'P10'], priority: 'Hoch' },

  // IT-08: MSP
  { id: 'IT-08-YES', description: { de: 'Shared MSP ja', en: 'Shared MSP yes' }, questionId: 'IT-08', answerCodes: ['YES'], policyPack: 'all', ruleRef: 'REG-031', effectCode: 'SUPPLIER_SHARED_SCOPE', effectText: { de: 'Shared MSP erhöht Scope und Lieferkettenrisiko.', en: 'Shared MSP increases scope and supply chain risk.' }, roadmapPacks: ['P8', 'P10'], priority: 'Hoch' },
  { id: 'IT-08-PARTIAL', description: { de: 'Shared MSP teilweise', en: 'Shared MSP partially' }, questionId: 'IT-08', answerCodes: ['PARTIAL'], policyPack: 'all', ruleRef: 'REG-033', effectCode: 'SUPPLIER_PARTIAL_SCOPE', effectText: { de: 'Partielle Trennung; Lieferkette dokumentieren.', en: 'Partial separation; document supply chain.' }, roadmapPacks: ['P8', 'P10'], priority: 'Mittel' },

  // IT-09: Segmentierung
  { id: 'IT-09-NONE', description: { de: 'Keine Segmentierung', en: 'No segmentation' }, questionId: 'IT-09', answerCodes: ['NONE'], policyPack: 'all', ruleRef: 'REG-033', effectCode: 'RESULT_C_NETWORK_FLAT', effectText: { de: 'Ohne Segmentierung praktisch kein begrenzbarer Scope.', en: 'Without segmentation, virtually no limiteable scope.' }, roadmapPacks: ['P5', 'P10'], priority: 'Hoch' },
  { id: 'IT-09-BASIC', description: { de: 'Rudimentäre Segmentierung', en: 'Basic segmentation' }, questionId: 'IT-09', answerCodes: ['BASIC'], policyPack: 'all', ruleRef: 'REG-033', effectCode: 'RESULT_C_PARTIAL_SEGMENTATION', effectText: { de: 'Nur partielle Trennung; Ergebnis C-Kandidat.', en: 'Only partial separation; Outcome C candidate.' }, roadmapPacks: ['P5', 'P10'], priority: 'Hoch' },
  { id: 'IT-09-TESTED', description: { de: 'Segmentierung getestet', en: 'Segmentation tested' }, questionId: 'IT-09', answerCodes: ['TESTED'], policyPack: 'all', ruleRef: 'REG-032', effectCode: 'SPLIT_CRITERION_SEGMENTATION_OK', effectText: { de: 'Unterstützt harte Trennung.', en: 'Supports hard separation.' }, roadmapPacks: ['P10'], priority: 'Hoch' },

  // IT-10: Wiederanlauf
  { id: 'IT-10-NO', description: { de: 'Kein getrennter Wiederanlauf', en: 'No separate recovery' }, questionId: 'IT-10', answerCodes: ['NO'], policyPack: 'all', ruleRef: 'REG-033', effectCode: 'NO_SPLIT_RECOVERY', effectText: { de: 'Harte Trennung nicht belegbar; BCM-Lücke.', en: 'Hard separation not provable; BCM gap.' }, roadmapPacks: ['P6', 'P10'], priority: 'Hoch' },
  { id: 'IT-10-PARTIAL', description: { de: 'Wiederanlauf teilweise', en: 'Recovery partially' }, questionId: 'IT-10', answerCodes: ['PARTIAL'], policyPack: 'all', ruleRef: 'REG-033', effectCode: 'PARTIAL_SPLIT_RECOVERY', effectText: { de: 'Partielle Trennung; Ergebnis C-Kandidat.', en: 'Partial separation; Outcome C candidate.' }, roadmapPacks: ['P6', 'P10'], priority: 'Mittel' },
  { id: 'IT-10-YES', description: { de: 'Wiederanlauf getrennt', en: 'Recovery separated' }, questionId: 'IT-10', answerCodes: ['YES'], policyPack: 'all', ruleRef: 'REG-032', effectCode: 'SPLIT_CRITERION_RECOVERY_OK', effectText: { de: 'Unterstützt harte Trennung.', en: 'Supports hard separation.' }, roadmapPacks: ['P6', 'P10'], priority: 'Mittel' },

  // IT-11: Asset-Liste
  { id: 'IT-11-NO', description: { de: 'Keine getrennte Asset-Liste', en: 'No separate asset list' }, questionId: 'IT-11', answerCodes: ['NO'], policyPack: 'all', ruleRef: 'REG-033', effectCode: 'NO_SPLIT_ASSETS', effectText: { de: 'Scope kann nicht sauber begrenzt werden.', en: 'Scope cannot be cleanly limited.' }, roadmapPacks: ['P9', 'P10'], priority: 'Hoch' },
  { id: 'IT-11-PARTIAL', description: { de: 'Asset-Liste teilweise', en: 'Asset list partially' }, questionId: 'IT-11', answerCodes: ['PARTIAL'], policyPack: 'all', ruleRef: 'REG-033', effectCode: 'PARTIAL_SPLIT_ASSETS', effectText: { de: 'Partielle Trennung; Ergebnis C-Kandidat.', en: 'Partial separation; Outcome C candidate.' }, roadmapPacks: ['P9', 'P10'], priority: 'Mittel' },
  { id: 'IT-11-YES', description: { de: 'Asset-Liste getrennt', en: 'Asset list separated' }, questionId: 'IT-11', answerCodes: ['YES'], policyPack: 'all', ruleRef: 'REG-032', effectCode: 'SPLIT_CRITERION_ASSETS_OK', effectText: { de: 'Unterstützt harte Trennung.', en: 'Supports hard separation.' }, roadmapPacks: ['P9', 'P10'], priority: 'Mittel' },

  // IT-12: Logging
  { id: 'IT-12-NO', description: { de: 'Kein getrenntes Logging', en: 'No separate logging' }, questionId: 'IT-12', answerCodes: ['NO'], policyPack: 'all', ruleRef: 'REG-033', effectCode: 'NO_SPLIT_LOGGING', effectText: { de: 'Ohne getrenntes Logging keine belastbare harte Trennung.', en: 'No reliable hard separation without separate logging.' }, roadmapPacks: ['P7', 'P10'], priority: 'Hoch' },
  { id: 'IT-12-PARTIAL', description: { de: 'Logging teilweise', en: 'Logging partially' }, questionId: 'IT-12', answerCodes: ['PARTIAL'], policyPack: 'all', ruleRef: 'REG-033', effectCode: 'PARTIAL_SPLIT_LOGGING', effectText: { de: 'Partielle Trennung; Ergebnis C-Kandidat.', en: 'Partial separation; Outcome C candidate.' }, roadmapPacks: ['P7', 'P10'], priority: 'Mittel' },
  { id: 'IT-12-YES', description: { de: 'Logging getrennt', en: 'Logging separated' }, questionId: 'IT-12', answerCodes: ['YES'], policyPack: 'all', ruleRef: 'REG-032', effectCode: 'SPLIT_CRITERION_LOGGING_OK', effectText: { de: 'Unterstützt harte Trennung.', en: 'Supports hard separation.' }, roadmapPacks: ['P7', 'P10'], priority: 'Mittel' },

  // IT-13: Impact-Nachweis
  { id: 'IT-13-NO', description: { de: 'Kein Impact-Nachweis', en: 'No impact proof' }, questionId: 'IT-13', answerCodes: ['NO'], policyPack: 'all', ruleRef: 'REG-060', effectCode: 'NO_NONIMPACT_PROOF', effectText: { de: 'Ohne Impact-Nachweis kein Ergebnis B.', en: 'No Outcome B without impact proof.' }, roadmapPacks: ['P10', 'P12'], priority: 'Hoch' },
  { id: 'IT-13-PARTIAL', description: { de: 'Impact-Nachweis teilweise', en: 'Impact proof partially' }, questionId: 'IT-13', answerCodes: ['PARTIAL'], policyPack: 'all', ruleRef: 'REG-060', effectCode: 'WEAK_NONIMPACT_PROOF', effectText: { de: 'Nachweisniveau zu schwach; Ergebnis D- oder C-Kandidat.', en: 'Evidence level too weak; Outcome D or C candidate.' }, roadmapPacks: ['P10', 'P12'], priority: 'Hoch' },
  { id: 'IT-13-YES', description: { de: 'Impact-Nachweis vorhanden', en: 'Impact proof available' }, questionId: 'IT-13', answerCodes: ['YES'], policyPack: 'all', ruleRef: 'REG-032', effectCode: 'SPLIT_CRITERION_IMPACT_OK', effectText: { de: 'Achtes Trennkriterium erfüllt.', en: 'Eighth separation criterion met.' }, roadmapPacks: ['P10'], priority: 'Hoch' },

  // ── EVI-01: Nachweisniveau ──
  { id: 'EVI-01-SELF', description: { de: 'Nur Selbstauskunft', en: 'Self-assessment only' }, questionId: 'EVI-01', answerCodes: ['SELF'], policyPack: 'all', ruleRef: 'REG-060', effectCode: 'EVIDENCE_WEAK', effectText: { de: 'Aussagekraft reduziert; Ergebnis D-Kandidat bei Grenzfällen.', en: 'Reduced reliability; Outcome D candidate in borderline cases.' }, roadmapPacks: ['P12'], priority: 'Hoch' },
  { id: 'EVI-01-INTERNAL', description: { de: 'Internes Dokument', en: 'Internal document' }, questionId: 'EVI-01', answerCodes: ['INTERNAL'], policyPack: 'all', ruleRef: 'REG-060', effectCode: 'EVIDENCE_INTERNAL', effectText: { de: 'Für Self-Audit brauchbar, für harte Trennung meist nicht ausreichend.', en: 'Usable for self-audit, usually insufficient for hard separation.' }, roadmapPacks: ['P9', 'P10'], priority: 'Mittel' },
  { id: 'EVI-01-TECH', description: { de: 'Technischer Nachweis', en: 'Technical evidence' }, questionId: 'EVI-01', answerCodes: ['TECH'], policyPack: 'all', ruleRef: 'REG-060', effectCode: 'EVIDENCE_TECH', effectText: { de: 'Belastbarkeit steigt; für viele Kontrollen ausreichend.', en: 'Reliability increases; sufficient for many controls.' }, roadmapPacks: ['P9'], priority: 'Niedrig' },
  { id: 'EVI-01-EXTERNAL', description: { de: 'Externer Audit', en: 'External audit' }, questionId: 'EVI-01', answerCodes: ['EXTERNAL'], policyPack: 'all', ruleRef: 'REG-060', effectCode: 'EVIDENCE_EXTERNAL', effectText: { de: 'Hohe Belastbarkeit; Voraussetzung für Ergebnis B besser erfüllt.', en: 'High reliability; better meets requirements for Outcome B.' }, roadmapPacks: ['P10'], priority: 'Niedrig' },
];
