import type { TrackerAufgabe, PflichtDokument, AufgabenStatus } from '@/lib/types';

// 21 Pflichtaufgaben (aus Caritas-Dokument Kap. 12.6 adaptiert für DRK)
export const TRACKER_AUFGABEN: Omit<TrackerAufgabe, 'verantwortlich' | 'notiz'>[] = [
  // Phase 1: Tage 1–30 – Grundlagen
  {
    id: 'TA-01',
    phase: 1,
    phaseLabel: 'Phase 1 (Tage 1–30)',
    titel: 'BSI-Registrierung: MUK einrichten',
    beschreibung: 'ELSTER-Organisationszertifikat beantragen (dauert 5+ Werktage postalisch). Mindestens 2 Personen registrieren.',
    rechtsgrundlage: '§§33–34 BSIG',
    fristTage: 5,
    prioritaet: 'kritisch',
    status: 'offen',
    bsiLink: 'https://www.bsi.bund.de/DE/Themen/Regulierte-Wirtschaft/NIS-2-regulierte-Unternehmen/NIS2-MUK/MUK_node.html',
  },
  {
    id: 'TA-02',
    phase: 1,
    phaseLabel: 'Phase 1 (Tage 1–30)',
    titel: 'BSI-Registrierung: portal.bsi.bund.de',
    beschreibung: 'Registrierung im BSI-Portal abschließen. Öffentliche IP-Adressen, Sektor (Gesundheitswesen → Rettungsdienst), Einstufung (bwE/wE) eintragen.',
    rechtsgrundlage: '§33 BSIG',
    fristTage: 7,
    prioritaet: 'kritisch',
    status: 'offen',
    bsiLink: 'https://portal.bsi.bund.de',
  },
  {
    id: 'TA-03',
    phase: 1,
    phaseLabel: 'Phase 1 (Tage 1–30)',
    titel: 'Meldeprozess für Sicherheitsvorfälle etablieren',
    beschreibung: 'Meldeweg-Dokument erstellen: Wer meldet was wann an wen? Notfall-Kontaktliste mit Mobilnummern. BSI-Portal-Zugänge für 2 Personen. Vorausgefüllte Meldeformulare.',
    rechtsgrundlage: '§32 BSIG',
    fristTage: 7,
    prioritaet: 'kritisch',
    status: 'offen',
    bsiLink: 'https://www.bsi.bund.de/DE/Themen/Regulierte-Wirtschaft/NIS-2-regulierte-Unternehmen/NIS2-Anleitung-Meldung/Anleitung-Meldung_node.html',
  },
  {
    id: 'TA-04',
    phase: 1,
    phaseLabel: 'Phase 1 (Tage 1–30)',
    titel: 'Geschäftsleitungsschulung terminieren & buchen',
    beschreibung: 'Pflichtschulung für alle Geschäftsleitenden (§38 Abs. 3 BSIG). Empfehlung: IHK-Akademie, TÜV, BIHK-Webinar-Reihe (kostenlos). Nachweis aufbewahren.',
    rechtsgrundlage: '§38 Abs. 3 BSIG',
    fristTage: 30,
    prioritaet: 'kritisch',
    status: 'offen',
    bsiLink: 'https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/NIS-2/nis-2-geschaeftsleitungsschulung.pdf',
  },
  {
    id: 'TA-05',
    phase: 1,
    phaseLabel: 'Phase 1 (Tage 1–30)',
    titel: 'IT-Sicherheitsbeauftragte/n (ISB) benennen',
    beschreibung: 'ISB intern benennen oder extern beauftragen. Direkte Berichtslinie an GL. Stellenbeschreibung dokumentieren. Mindestens 0,5 VZÄ einplanen.',
    rechtsgrundlage: '§38 BSIG (implizit)',
    fristTage: 30,
    prioritaet: 'hoch',
    status: 'offen',
  },
  {
    id: 'TA-06',
    phase: 1,
    phaseLabel: 'Phase 1 (Tage 1–30)',
    titel: 'MFA für Admin-Konten und VPN aktivieren',
    beschreibung: 'Quick-Win: MFA sofort für alle Administrator-Accounts und VPN-Zugänge einschalten. Wenn Microsoft 365 vorhanden: Microsoft Authenticator (im Lizenzpreis enthalten).',
    rechtsgrundlage: '§30 Nr. 10 BSIG',
    fristTage: 30,
    prioritaet: 'hoch',
    status: 'offen',
    bsiLink: 'https://www.bsi.bund.de/dok/nis-2-infopakete',
  },
  {
    id: 'TA-07',
    phase: 1,
    phaseLabel: 'Phase 1 (Tage 1–30)',
    titel: 'IT-Asset-Bestandsaufnahme starten',
    beschreibung: 'Alle IT-Systeme, Server, Anwendungen, Cloud-Dienste erfassen. Ziel: 80% Vollständigkeit in Phase 1. Für Rettungsdienst-IT getrennte Liste anlegen.',
    rechtsgrundlage: '§30 Nr. 9 BSIG',
    fristTage: 30,
    prioritaet: 'hoch',
    status: 'offen',
  },
  // Phase 2: Tage 31–60 – Strukturaufbau
  {
    id: 'TA-08',
    phase: 2,
    phaseLabel: 'Phase 2 (Tage 31–60)',
    titel: 'Gap-Analyse §30 BSIG durchführen',
    beschreibung: 'Ist-Zustand systematisch gegen alle 10 Mindestmaßnahmen des §30 BSIG abgleichen. Externer Berater sinnvoll. BSI CyberRisikoCheck nutzen.',
    rechtsgrundlage: '§30 BSIG',
    fristTage: 60,
    prioritaet: 'mittel',
    status: 'offen',
  },
  {
    id: 'TA-09',
    phase: 2,
    phaseLabel: 'Phase 2 (Tage 31–60)',
    titel: 'Risikoanalyse (erste Version)',
    beschreibung: 'Kritische Assets identifizieren. Bedrohungen bewerten. Risikobehandlungsplan erstellen. Fokus zuerst auf Rettungsdienst-IT.',
    rechtsgrundlage: '§30 Nr. 1 BSIG',
    fristTage: 60,
    prioritaet: 'mittel',
    status: 'offen',
    bsiLink: 'https://www.bsi.bund.de/dok/nis-2-infopakete',
  },
  {
    id: 'TA-10',
    phase: 2,
    phaseLabel: 'Phase 2 (Tage 31–60)',
    titel: 'ISMS-Framework entscheiden',
    beschreibung: 'Entscheidung zwischen ISO 27001, BSI IT-Grundschutz oder CISIS12. Für DRK-KV mit Rettungsdienst: ISO 27001 empfohlen. Entscheidung dokumentieren und freigeben.',
    rechtsgrundlage: '§30 Nr. 1 BSIG',
    fristTage: 60,
    prioritaet: 'mittel',
    status: 'offen',
  },
  {
    id: 'TA-11',
    phase: 2,
    phaseLabel: 'Phase 2 (Tage 31–60)',
    titel: 'Informationssicherheitsleitlinie erstellen',
    beschreibung: 'Einseitiges bis dreiseitiges Grundsatzdokument. Von Geschäftsleitung verabschieden lassen. Im gesamten Kreisverband kommunizieren.',
    rechtsgrundlage: '§30 Nr. 1 BSIG',
    fristTage: 60,
    prioritaet: 'mittel',
    status: 'offen',
  },
  {
    id: 'TA-12',
    phase: 2,
    phaseLabel: 'Phase 2 (Tage 31–60)',
    titel: 'Backup-Situation auditieren',
    beschreibung: '3-2-1-Regel prüfen: 3 Kopien, 2 Medientypen, 1 offline/air-gapped. Restore-Test durchführen und dokumentieren. Immutable Backups einrichten.',
    rechtsgrundlage: '§30 Nr. 3 BSIG',
    fristTage: 60,
    prioritaet: 'mittel',
    status: 'offen',
  },
  {
    id: 'TA-13',
    phase: 2,
    phaseLabel: 'Phase 2 (Tage 31–60)',
    titel: 'Incident-Response-Plan (Entwurf)',
    beschreibung: 'Eskalationsstufen, Rollen, Kommunikationswege definieren. 24/7-Erreichbarkeit sicherstellen. BSI-Meldepflichten integrieren.',
    rechtsgrundlage: '§30 Nr. 2 BSIG',
    fristTage: 60,
    prioritaet: 'mittel',
    status: 'offen',
  },
  {
    id: 'TA-14',
    phase: 2,
    phaseLabel: 'Phase 2 (Tage 31–60)',
    titel: 'Lieferantenverzeichnis erstellen',
    beschreibung: 'Alle IT-Dienstleister, Cloud-Anbieter, Software-Lieferanten erfassen. Kritikalitätsbewertung je Lieferant. Bestehende Verträge auf Sicherheitsklauseln prüfen.',
    rechtsgrundlage: '§30 Nr. 4 BSIG',
    fristTage: 60,
    prioritaet: 'mittel',
    status: 'offen',
  },
  // Phase 3: Tage 61–90 – Implementierung
  {
    id: 'TA-15',
    phase: 3,
    phaseLabel: 'Phase 3 (Tage 61–90)',
    titel: 'Geschäftsleitungsschulung durchführen',
    beschreibung: 'Schulung absolvieren. Zertifikat/Nachweis mit Datum und Inhalten aufbewahren (wichtigstes Haftungsschutz-Dokument).',
    rechtsgrundlage: '§38 Abs. 3 BSIG',
    fristTage: 90,
    prioritaet: 'kritisch',
    status: 'offen',
  },
  {
    id: 'TA-16',
    phase: 3,
    phaseLabel: 'Phase 3 (Tage 61–90)',
    titel: 'Security-Awareness-Training für alle Mitarbeitenden starten',
    beschreibung: 'Phishing-Erkennung, sichere Passwörter, Meldeweg. Rettungsdienst-Personal im Schichtdienst berücksichtigen (Kurzvideos, mobile-fähig). Erste Runde dokumentieren.',
    rechtsgrundlage: '§30 Nr. 7 BSIG',
    fristTage: 90,
    prioritaet: 'hoch',
    status: 'offen',
  },
  {
    id: 'TA-17',
    phase: 3,
    phaseLabel: 'Phase 3 (Tage 61–90)',
    titel: 'Schwachstellen-Scan aller extern erreichbaren Systeme',
    beschreibung: 'Externer oder interner Scan. Kritische Schwachstellen sofort patchen. Bericht dokumentieren.',
    rechtsgrundlage: '§30 Nr. 5 BSIG',
    fristTage: 90,
    prioritaet: 'mittel',
    status: 'offen',
  },
  {
    id: 'TA-18',
    phase: 3,
    phaseLabel: 'Phase 3 (Tage 61–90)',
    titel: 'Business Impact Analyse (BIA)',
    beschreibung: 'Geschäftskritische Prozesse identifizieren. RTO/RPO für Rettungsdienst-IT festlegen. Ergebnis dokumentieren.',
    rechtsgrundlage: '§30 Nr. 3 BSIG',
    fristTage: 90,
    prioritaet: 'mittel',
    status: 'offen',
  },
  {
    id: 'TA-19',
    phase: 3,
    phaseLabel: 'Phase 3 (Tage 61–90)',
    titel: 'Lieferantenverträge: Sicherheitsklauseln ergänzen',
    beschreibung: 'Cybersicherheitsanforderungen, Meldepflichten, Audit-Rechte in bestehende und neue Verträge aufnehmen. Muster-Klausel verwenden.',
    rechtsgrundlage: '§30 Nr. 4 BSIG',
    fristTage: 90,
    prioritaet: 'mittel',
    status: 'offen',
  },
  {
    id: 'TA-20',
    phase: 3,
    phaseLabel: 'Phase 3 (Tage 61–90)',
    titel: 'Netzwerksegmentierung planen',
    beschreibung: 'Rettungsdienst-IT, Verwaltung, Gäste-WLAN segmentieren. Netzwerkplan mit Sicherheitszonen erstellen. Umsetzung in Phase 4.',
    rechtsgrundlage: '§30 Nr. 5 BSIG',
    fristTage: 90,
    prioritaet: 'mittel',
    status: 'offen',
  },
  {
    id: 'TA-21',
    phase: 3,
    phaseLabel: 'Phase 3 (Tage 61–90)',
    titel: '12-Monats-ISMS-Roadmap erstellen',
    beschreibung: 'Detaillierter Projektplan für ISMS-Aufbau und Zertifizierung (ISO 27001 dauert 9–18 Monate). Meilensteine, Verantwortliche, Budget.',
    rechtsgrundlage: 'ISO 27001 / §30 BSIG',
    fristTage: 90,
    prioritaet: 'mittel',
    status: 'offen',
  },
];

// 18 Pflichtdokumente nach §30 BSIG (aus Caritas-Dokument Kap. 12.11)
export const PFLICHT_DOKUMENTE: Omit<PflichtDokument, 'verantwortlich' | 'vorhandeneVersion'>[] = [
  { id: 'PD-01', nummer: 1,  titel: 'Informationssicherheitsleitlinie', beschreibung: 'Von GL verabschiedetes Grundsatzdokument (1–3 Seiten)', rechtsgrundlage: '§30 Nr. 1 BSIG', status: 'offen' },
  { id: 'PD-02', nummer: 2,  titel: 'Risikoanalyse', beschreibung: 'Systematische Bewertung aller IT-Risiken', rechtsgrundlage: '§30 Nr. 1 BSIG', status: 'offen' },
  { id: 'PD-03', nummer: 3,  titel: 'Risikobehandlungsplan', beschreibung: 'Maßnahmen zu jedem identifizierten Risiko', rechtsgrundlage: '§30 Nr. 1 BSIG', status: 'offen' },
  { id: 'PD-04', nummer: 4,  titel: 'Statement of Applicability (SoA)', beschreibung: 'Erklärung zur Anwendbarkeit aller Maßnahmen', rechtsgrundlage: 'ISO 27001', status: 'offen' },
  { id: 'PD-05', nummer: 5,  titel: 'IT-Asset-Inventar', beschreibung: 'Alle Systeme mit Klassifikation und Schutzbedarf', rechtsgrundlage: '§30 Nr. 9 BSIG', status: 'offen' },
  { id: 'PD-06', nummer: 6,  titel: 'Incident-Response-Plan', beschreibung: 'Eskalationsstufen, Rollen, Kommunikationswege, Meldefristen', rechtsgrundlage: '§30 Nr. 2 + §32 BSIG', status: 'offen' },
  { id: 'PD-07', nummer: 7,  titel: 'Business Continuity Plan', beschreibung: 'Notfallplan für kritische Dienste', rechtsgrundlage: '§30 Nr. 3 BSIG', status: 'offen' },
  { id: 'PD-08', nummer: 8,  titel: 'Disaster Recovery Plan', beschreibung: 'Technischer Wiederherstellungsplan', rechtsgrundlage: '§30 Nr. 3 BSIG', status: 'offen' },
  { id: 'PD-09', nummer: 9,  titel: 'Backup-Konzept', beschreibung: '3-2-1-Regel, Restore-Test-Protokolle', rechtsgrundlage: '§30 Nr. 3 BSIG', status: 'offen' },
  { id: 'PD-10', nummer: 10, titel: 'Lieferantenverzeichnis', beschreibung: 'Alle IT-Dienstleister mit Kritikalitätsbewertung', rechtsgrundlage: '§30 Nr. 4 BSIG', status: 'offen' },
  { id: 'PD-11', nummer: 11, titel: 'Lieferantenverträge mit Sicherheitsklauseln', beschreibung: 'Cybersicherheitsanforderungen, Meldepflichten, Audit-Rechte', rechtsgrundlage: '§30 Nr. 4 BSIG', status: 'offen' },
  { id: 'PD-12', nummer: 12, titel: 'Zugriffsrechte-Dokumentation', beschreibung: 'Wer hat Zugriff auf was, wann zuletzt überprüft', rechtsgrundlage: '§30 Nr. 9 BSIG', status: 'offen' },
  { id: 'PD-13', nummer: 13, titel: 'Schulungsnachweise', beschreibung: 'Alle Mitarbeitenden + Geschäftsleitung, Datum, Inhalte', rechtsgrundlage: '§30 Nr. 7 + §38 BSIG', status: 'offen' },
  { id: 'PD-14', nummer: 14, titel: 'Audit-Berichte', beschreibung: 'Interne/externe Audit-Ergebnisse und Korrekturmaßnahmen', rechtsgrundlage: '§30 Nr. 6 BSIG', status: 'offen' },
  { id: 'PD-15', nummer: 15, titel: 'Maßnahmenplan', beschreibung: 'Priorisierter Plan mit Verantwortlichkeiten und Terminen', rechtsgrundlage: '§30 BSIG', status: 'offen' },
  { id: 'PD-16', nummer: 16, titel: 'Kryptographie-Konzept', beschreibung: 'Verwendete Verfahren, Schlüsselmanagement', rechtsgrundlage: '§30 Nr. 8 BSIG', status: 'offen' },
  { id: 'PD-17', nummer: 17, titel: 'Netzwerkplan mit Sicherheitszonen', beschreibung: 'Dokumentierte Segmentierung', rechtsgrundlage: '§30 Nr. 5 BSIG', status: 'offen' },
  { id: 'PD-18', nummer: 18, titel: 'Meldeprozess-Dokument', beschreibung: 'Wer meldet was wann an wen (inkl. BSI, DSGVO)', rechtsgrundlage: '§32 BSIG + Art. 33 DSGVO', status: 'offen' },
];
